# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-12 08:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_auto_20190812_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_space_number', models.CharField(max_length=4)),
                ('long', models.DecimalField(decimal_places=2, max_digits=8)),
                ('lat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('finish_date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('parking_space', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservation.ParkingSpace')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.Profile')),
            ],
        ),
    ]
