# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-12 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20190812_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='FREE', max_length=10),
        ),
    ]
