# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-12 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
