# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-12 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20190812_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
